server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    maxThreads: 500
    uriEncoding: utf-8

eureka: 
  client: 
    registerWithEureka: false
    fetchRegistry: false

management:
  server:
    port: 8088

spring: 
  profiles: 
    active: local
  mvc:
    contentnegotiation:
      favor-path-extension: true
    pathmatch:
      use-suffix-pattern: true
      matching-strategy: ant_path_matcher
    favicon:
      enabled: false
  freemarker:
    expose-request-attributes: true
    request-context-attribute: request
    suffix: .html
    settings:
      number_format: computer
  jackson:
    default-property-inclusion: NON_NULL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource
    tomcat: 
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 30000
      min-evictable-idle-time-millis: 55000
      num-tests-per-eviction-run: 20
      remove-abandoned: true
      remove-abandoned-timeout: 180
      log-abandoned: true
  main:
    allow-circular-references: true

mqcloud:
  repositoryUrl: https://私有仓库/nexus/content/groups/public
  clientArtifactId: mq-client-open
  producerClass:  RocketMQProducer
  consumerClass: RocketMQConsumer
  ticketKey: ticket #cas登录返回后的key，用户名密码可以忽略
  autoAuditType: 5,6,7,8,12,13,16,17,18,19,20,22,24 #自动审核类型，值来自：com.sohu.tv.mq.cloud.bo.Audit.TypeEnum
  threadMetricSupportedVersion: 4.7.2
  consumeFailedMetricSupportedVersion: 4.7.2
  consumeTimespanMessageSupportedVersion: 4.9.2
  httpProducerUriPrefix: 127.0.0.1:8081/http/producer
  httpConsumerUriPrefix: 127.0.0.1:8082/http/consumer
  loginClass: com.sohu.tv.mq.cloud.service.impl.DefaultLoginService
  userWarnServiceClass: com.sohu.tv.mq.cloud.service.UserWarnService
  mailClass: com.sohu.tv.mq.cloud.service.impl.DefaultMailSender

rocketmq:
  customized: true
task:
  enabled: true